### 1.Register / Signup
POST http://localhost:9091/api/auth/local/register
Content-Type: application/json

{
  "username": "kittikoon",
  "email": "kittikoon-p@rmutp.ac.th",
  "password": "kittikoon@0911646466"
}

### 2.Login User
POST http://localhost:9091/api/auth/local
Content-Type: application/json

{
  "identifier": "kittikoon-p@rmutp.ac.th",
  "password": "kittikoon@0911646466"
}

### 3.Login Admin
POST http://localhost:9091/admin/login
Content-Type: application/json

{
  "email": "kittikoon-p@rmutp.ac.th",
  "password": "kittikoon@0911646466",
  "rememberMe": false
}

### 4.Forgot Password
POST http://localhost:9091/api/auth/forgot-password
Content-Type: application/json

{
  "email": "kittikoon-p@rmutp.ac.th"
}

### 5.Profile
GET http://localhost:9091/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg3NjcyNDA5LCJleHAiOjE3OTAyNjQ0MDl9.nTyIqZqY5PFdZPn3omd3oWSrT713-JnZswO3VPrqJ9c